# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e65e8f55406724481e650cbc41f1879d"
name = "discount-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_discounts"
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[discount.metafields.app.function-configuration]
type = "json"
name = "Function Configuration"
access.admin = "merchant_read_write"
access.storefront = "none"
