api_version = "2026-01"

[[extensions]]
name = "t:name"
description = "t:description"
handle = "discount-ui"
uid = "f6baafa8-f19b-bf57-f937-33b933966408d5eddb64"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/DiscountFunctionSettings.jsx"
target = "admin.discount-details.function-settings.render"

[[extensions.metafields]]
namespace = "$app"
key = "function-configuration"
